"""
Service for managing Payment Transactions and Invoicing logic.
Orchestrates payments via gateways and provisions credits.
"""
import logging
import json
from typing import Dict, Any, Optional
from datetime import datetime, timedelta

from domain.entities.billing_models import PaymentProvider, PaymentStatus, PaymentTransaction, Invoice
from ports.data_persistence import DataPersistencePort
from ports.payment_gateway import PaymentGatewayPort

logger = logging.getLogger(__name__)

class PaymentService:
    def __init__(
        self,
        data_persistence_adapter: DataPersistencePort,
        stripe_gateway: PaymentGatewayPort,
        paypal_gateway: PaymentGatewayPort,
        credit_service: Any,  # Inject CreditService to provision
        gateway_configs: Optional[Dict[PaymentProvider, Dict[str, Any]]] = None,
        hook_manager=None,
    ):
        self.data_persistence = data_persistence_adapter
        self.stripe = stripe_gateway
        self.paypal = paypal_gateway
        self.credit_service = credit_service
        self.gateway_configs = gateway_configs or {}
        self.hook_manager = hook_manager

    def _get_gateway(self, provider: PaymentProvider) -> PaymentGatewayPort:
        return self.stripe if provider == PaymentProvider.STRIPE else self.paypal

    def _get_gateway_config(self, provider: PaymentProvider) -> Optional[Dict[str, Any]]:
        """Get gateway configuration from database or fallback to env vars"""
        return self.gateway_configs.get(provider)

    def get_active_credit_packages(self):
        return self.data_persistence.get_active_credit_packages()

    def get_user_invoices(self, user_id: int, page: int = 1, page_size: int = 20):
        return self.data_persistence.get_user_invoices(user_id, page, page_size)

    def get_user_transactions(self, user_id: int, page: int = 1, page_size: int = 20):
        return self.data_persistence.get_payment_transactions(user_id=user_id, page=page, page_size=page_size)

    def get_invoice_by_id(self, invoice_id: str):
        return self.data_persistence.get_invoice_by_id(invoice_id)

    def initialize_payment(self, user_id: int, provider: PaymentProvider, amount: float, currency: str, package_id: Optional[int] = None) -> tuple[str, Dict[str, str]]:
        """
        Start an order for the selected credit package.
        Returns a tuple: (internal_transaction_id, gateway_specific_initialization_data).
        """
        package = None
        credits = 0
        
        if package_id:
            package = self.data_persistence.get_credit_package_by_id(package_id)
            if not package or not package.is_active:
                raise ValueError("Invalid or inactive credit package.")
            amount_to_charge = package.amount
            currency_to_charge = package.currency
            credits = package.credits
        else:
            amount_to_charge = amount
            currency_to_charge = currency
            # For custom amounts, calculate credits (1:1 ratio - can be adjusted)
            credits = int(amount_to_charge)

        gateway = self._get_gateway(provider)
        # We pass user_id and package_id as reference data to the gateway
        order_meta = gateway.create_order(
            amount=amount_to_charge,
            currency=currency_to_charge,
            reference_id=f"usr_{user_id}_pkg_{package_id or 'custom'}"
        )

        # Create AWAITING_PAYMENT transaction in DB (user has not completed checkout yet)
        # Use package_id if available, otherwise None for custom amounts
        transaction_package_id = package_id if package_id else None
        transaction = PaymentTransaction(
            id="", # Generated by persistence
            user_id=user_id,
            package_id=transaction_package_id,
            provider=provider,
            provider_transaction_id=order_meta.get("id"),
            status=PaymentStatus.AWAITING_PAYMENT,
            amount=amount_to_charge,
            currency=currency_to_charge
        )
        self.data_persistence.create_payment_transaction(transaction)

        return (transaction.id, order_meta)

    def resume_payment_order(self, user_id: int, transaction_id: str) -> Dict[str, Any]:
        """
        Resumes an existing AWAITING_PAYMENT transaction.
        Checks DB state and fetches the fresh provider intent data.
        """
        transaction = self.data_persistence.get_payment_transaction_by_id(transaction_id)
        if not transaction or transaction.user_id != user_id:
            raise ValueError("Transaction not found or unauthorized.")

        if transaction.status != PaymentStatus.AWAITING_PAYMENT:
            raise ValueError(f"Transaction cannot be resumed from status: {transaction.status}")
            
        if not transaction.provider_transaction_id:
            raise ValueError("Provider transaction ID is missing.")

        gateway = self._get_gateway(transaction.provider)
        order_meta = gateway.resume_order(transaction.provider_transaction_id)

        return order_meta

    def capture_payment(self, user_id: int, provider_order_id: str, provider: PaymentProvider) -> PaymentTransaction:
        """
        Synchronously captures the payment (mostly used by PayPal flow).
        Checks DB state to prevent double provisioning.
        """
        transaction = self.data_persistence.get_payment_transaction_by_provider_id(provider_order_id)
        if not transaction or transaction.user_id != user_id:
            raise ValueError("Transaction not found or unauthorized.")

        if transaction.status == PaymentStatus.COMPLETED:
            # Idempotency return
            return transaction

        gateway = self._get_gateway(provider)
        is_captured = gateway.capture_order(provider_order_id)

        if is_captured:
            # 1. Update Transaction
            transaction.status = PaymentStatus.COMPLETED
            self.data_persistence.update_payment_transaction(transaction)
            
            # 2. Add Ledger Entry (Capacity Block)
            credits = 0
            package = None
            if transaction.package_id:
                package = self.data_persistence.get_credit_package_by_id(transaction.package_id)
                if package:
                    credits = package.credits
            else:
                # For custom amounts without a package, calculate credits from the transaction amount
                credits = int(transaction.amount)
                
            # Create Ledger happens inside DB Adapter in a standard atomic transaction
            self.data_persistence.create_ledger_entry_from_purchase(transaction.id, credits)

            self._fire_credit_purchased(transaction, credits)

            # 3. Create Enterprise Invoice
            self._create_enterprise_invoice(transaction, package, credits, provider, provider_order_id)

            return transaction
        else:
            transaction.status = PaymentStatus.FAILED
            self.data_persistence.update_payment_transaction(transaction)
            raise RuntimeError("Payment Capture Failed at Provider.")

    def process_webhook(self, provider: PaymentProvider, headers: Dict[str, str], payload: bytes) -> bool:
        """
        Asynchronous webhook processing. Captures payments automatically if not already captured.
        """
        gateway = self._get_gateway(provider)
        
        try:
            # 1. Validate signature cryptographically using Gateway Adapter
            event_data = gateway.validate_webhook_signature(headers, payload)
        except Exception as e:
            logger.error(f"Webhook Signature Validation Failed: {e}")
            raise ValueError("Invalid Webhook Signature")

        # 2. Extract provider order/intent ID from the event and get transactional state
        provider_order_id = gateway.extract_transaction_id_from_webhook(event_data)
        if not provider_order_id:
            return True # Not a payment event we care about

        transaction = self.data_persistence.get_payment_transaction_by_provider_id(provider_order_id)
        if not transaction:
            logger.warning(f"Webhook received for unknown transaction {provider_order_id}")
            return True
            
        if transaction.status == PaymentStatus.COMPLETED:
            logger.info(f"Webhook received for already completed transaction {provider_order_id}")
             # Idempotency exit. It was probably captured synchronously by the frontend.
            return True

        # Check if the event signifies success
        if gateway.is_webhook_payment_successful(event_data):
            # Mark completed, provision ledger, create invoice
            transaction.status = PaymentStatus.COMPLETED
            self.data_persistence.update_payment_transaction(transaction)
            
            # Get credits - handle case where package_id might be None
            credits = 0
            package = None
            if transaction.package_id:
                package = self.data_persistence.get_credit_package_by_id(transaction.package_id)
                if package:
                    credits = package.credits
            else:
                # For custom amounts without a package, calculate credits from the transaction amount
                credits = int(transaction.amount)
                
            self.data_persistence.create_ledger_entry_from_purchase(transaction.id, credits)
            self._fire_credit_purchased(transaction, credits)
            self._create_enterprise_invoice(transaction, package, credits, provider, provider_order_id)
            return True
            
        elif gateway.is_webhook_payment_failed(event_data):
             transaction.status = PaymentStatus.FAILED
             self.data_persistence.update_payment_transaction(transaction)
             return True
             
        return True

    def _create_enterprise_invoice(self, transaction: PaymentTransaction, package: Any, credits: int, provider: PaymentProvider, provider_transaction_id: str):
        """Create enterprise-grade invoice for a completed transaction"""
        user = self.data_persistence.get_user(transaction.user_id)
        
        # Build line items as JSON
        line_items = []
        if package:
            line_items.append({
                "name": package.name,
                "description": f"{package.credits} Credits - {package.description or 'Credit Package'}",
                "quantity": 1,
                "unit_price": package.amount,
                "total": package.amount
            })
        else:
            # Custom amount
            line_items.append({
                "name": "Custom Credit Purchase",
                "description": f"{credits} Credits",
                "quantity": 1,
                "unit_price": transaction.amount,
                "total": transaction.amount
            })
        
        # Calculate amounts
        subtotal = transaction.amount
        tax_rate = 0.0  # Can be configured based on region
        tax_amount = round(subtotal * tax_rate, 2)
        total = subtotal + tax_amount
        
        # Get billing name from user
        billing_name = "Customer"
        if user:
            if hasattr(user, 'first_name') and user.first_name:
                billing_name = f"{user.first_name} {user.last_name or ''}".strip()
            elif hasattr(user, 'username') and user.username:
                billing_name = user.username
        
        # Get billing address if available
        billing_address = {}
        if user and hasattr(user, 'address'):
            billing_address = user.address or {}
        
        now = datetime.utcnow()
        
        invoice = Invoice(
            id="",  # Generated by persistence
            transaction_id=transaction.id,
            user_id=transaction.user_id,
            invoice_number=f"INV-{transaction.id[:8].upper()}",
            
            # Payment Information
            provider=provider,
            provider_transaction_id=provider_transaction_id,
            
            # Amount Breakdown
            subtotal_amount=subtotal,
            tax_amount=tax_amount,
            total_amount=total,
            currency=transaction.currency,
            
            # Billing Information
            billing_email=user.email if user else "unknown",
            billing_name=billing_name,
            billing_address_line1=billing_address.get('line1'),
            billing_address_line2=billing_address.get('line2'),
            billing_city=billing_address.get('city'),
            billing_state=billing_address.get('state'),
            billing_postal_code=billing_address.get('postal_code'),
            billing_country=billing_address.get('country'),
            
            # Line Items
            line_items=json.dumps(line_items),
            
            # Tax & Business Information
            tax_rate=tax_rate if tax_rate > 0 else None,
            tax_id=None,  # Can be set if business has VAT/GST number
            
            # Invoice Status & Dates
            status="paid",
            invoice_date=now,
            due_date=now,  # Immediate payment
            paid_at=now,
            
            # Metadata
            notes=f"Payment via {provider.value}. Transaction: {provider_transaction_id}",
            created_at=now
        )
        self.data_persistence.create_invoice(invoice)
        logger.info(f"Enterprise Invoice {invoice.invoice_number} created for transaction {transaction.id} via {provider.value}")
        return invoice

    def create_pending_invoice(self, transaction: PaymentTransaction, package: Any, description: str, due_date: datetime, notes: Optional[str]) -> Invoice:
        """Create an invoice for a pending payment"""
        user = self.data_persistence.get_user(transaction.user_id)
        
        # Build line items
        line_items = []
        if package:
            line_items.append({
                "name": package.name,
                "description": f"{package.credits} Credits - {package.description or 'Credit Package'}",
                "quantity": 1,
                "unit_price": package.amount,
                "total": package.amount
            })
        else:
            line_items.append({
                "name": description or "Custom Credit Purchase",
                "description": f"{int(transaction.amount)} Credits",
                "quantity": 1,
                "unit_price": transaction.amount,
                "total": transaction.amount
            })
        
        # Calculate amounts
        subtotal = transaction.amount
        tax_rate = 0.0
        tax_amount = round(subtotal * tax_rate, 2)
        total = subtotal + tax_amount
        
        billing_name = "Customer"
        if user:
            if hasattr(user, 'first_name') and user.first_name:
                billing_name = f"{user.first_name} {user.last_name or ''}".strip()
            elif hasattr(user, 'username') and user.username:
                billing_name = user.username
        
        now = datetime.utcnow()
        import json
        
        invoice = Invoice(
            id="",  # Generated by persistence
            transaction_id=transaction.id,
            user_id=transaction.user_id,
            invoice_number=f"INV-{transaction.id[:8].upper()}",
            
            # Payment Information
            provider=transaction.provider,
            provider_transaction_id=None,  # Will be set when paid
            
            # Amount Breakdown
            subtotal_amount=subtotal,
            tax_amount=tax_amount,
            total_amount=total,
            currency=transaction.currency,
            
            # Billing Information
            billing_email=user.email if user else "unknown",
            billing_name=billing_name,
            
            # Line Items
            line_items=json.dumps(line_items),
            
            # Invoice Status & Dates
            status="pending",  # Invoice is pending payment
            invoice_date=now,
            due_date=due_date,
            paid_at=None,  # Not paid yet
            
            # Metadata
            notes=notes or f"Admin-generated invoice. {description}",
            created_at=now
        )
        
        invoice_id = self.data_persistence.create_invoice(invoice)
        invoice.id = invoice_id
        return invoice

    def _fire_credit_purchased(self, transaction: PaymentTransaction, credits: int) -> None:
        """Fire CREDIT_PURCHASED event after successful credit provisioning."""
        if not self.hook_manager:
            return
        from ports.hooks.base_handler import HookEvent, HookEventType
        self.hook_manager.fire(HookEvent(
            event_type=HookEventType.CREDIT_PURCHASED,
            data={
                "user_id": transaction.user_id,
                "credits": credits,
                "amount": float(transaction.amount),
                "currency": transaction.currency,
                "provider": transaction.provider.value if hasattr(transaction.provider, "value") else str(transaction.provider),
                "package_id": transaction.package_id,
            },
            source="payment_service",
        ))
